# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
pool:
  name: Default
stages:
- stage: Build1
  jobs:
    - job:
      steps:
      - powershell: Start-Sleep -Seconds 5
        displayName: 'script 1'
